### ISSUE TITLE
How to show spinner on top part of container

### ISSUE THREAD

**Issue by f3l1xss** [Zak-C/ngx-loading#115] opened 2020-08-24 18:55 UTC
Hi there, when having parent with long height, Spinner will still be displayed in the center of the parent which will typically cause it to be invisible. 
Is there any way to force the spinner to be at the top middle part?

FullScreen is not an option to me since I want some element in my DOM to be displayed when loading

**Comment by Zak-C** [comment] 2022-03-03 16:13
Duplicate of https://github.com/Zak-C/ngx-loading/issues/6

**Closed by Zak-C** 2022-03-03 16:13 UTC
Labels: enhancement
